


// try {
//     console.log(variavelInexistente);
// } catch (error: any) {
//     console.log("Ocorreu um erro:\n", error.message);
// } finally {
//     console.log("Bloco finally executado");
// }

// function dividir(a: number, b: number): number {
//     if (b === 0) {
//         throw new Error("Divisão por zero não é permitida");
//     }
//     return a / b;
// }


// try {
//     console.log(dividir(10, 0));
// } catch (error: any) {
//     console.log("Ocorreu um erro:\n", error.message);

// }

// // console.log(variavelInexistente);

// try {
// console.log(variavelInexistente);
// } catch (error: any) {
// console.log("Ocorreu um erro:\n", error.message);
// }
// console.log("Execução continua normalmente ... ");
